/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { MeshProps } from "@react-three/fiber";

export const GLTF_PATH = "/box.glb";

export function PackageMesh(props: MeshProps) {
  const { nodes, materials } = useGLTF(GLTF_PATH);
  return (
    <mesh {...props} dispose={null}>
      <group scale={5.37}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={(nodes.defaultMaterial004 as THREE.Mesh).geometry}
            material={materials.MAT_CardBoardBox}
            position={[-0.023, 0.04, 0.01]}
            scale={0.53}
          />
        </group>
      </group>
    </mesh>
  );
}

useGLTF.preload(GLTF_PATH);