import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";
import { useRef } from "react";


export function RobotMesh(props: GroupProps) {
    const mesh = useRef(null);
    const { nodes, materials } = useGLTF("/Forklift_agv_01.glb");

    // Auto-generated by: https://github.com/pmndrs/gltfjsx
    return (
        <group {...props} dispose={null} ref={mesh}>
          <group position={[0, 0.02, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.75}>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Circle as THREE.Mesh).geometry}
              material={materials["CW Anodized med.004"]}
              position={[0.27, 0.66, -0.18]}
              rotation={[0.6, 0, 0]}
              scale={0.25}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube as THREE.Mesh).geometry}
              material={materials["CW Plastic dapple.003"]}
              position={[0.01, 0.28, -0.01]}
              scale={0.25}
            />
            <group
              position={[0.11, 0.55, 0.12]}
              rotation={[0, 0, -0.44]}
              scale={0.35}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube009 as THREE.Mesh).geometry}
                material={materials["Material.021"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube009_1 as THREE.Mesh).geometry}
                material={materials["Material.019"]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube002 as THREE.Mesh).geometry}
              material={materials.Chocofur_Flowers_01_004}
              position={[0.01, 0.28, -0.01]}
              scale={0.25}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube004 as THREE.Mesh).geometry}
              material={materials["CW Anodized med.004"]}
              position={[0.16, 0.33, -0.17]}
              scale={0.25}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube003 as THREE.Mesh).geometry}
                material={materials["CW Anodized med.004"]}
                position={[0.11, -0.51, -0.55]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Plane002 as THREE.Mesh).geometry}
                material={materials["Material.006"]}
                position={[-0.62, -0.73, -1.49]}
                rotation={[0, Math.PI / 2, 0]}
                scale={2.31}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube005 as THREE.Mesh).geometry}
              material={materials["CW Plastic dapple.003"]}
              position={[0.16, 0.21, -0.17]}
              scale={0.25}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035006 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[0.31, 4.87, 0.25]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035007 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[0.31, 5.4, 0.24]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035008 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[0.31, 4.87, 0.52]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035009 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[0.31, 5.4, 0.52]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Signs_004_OCP as THREE.Mesh).geometry}
                material={materials[".Signs_004_O.C.P"]}
                position={[-0.66, 5.13, 0.91]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.29}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Signs_004_OCP_projected as THREE.Mesh).geometry}
                material={materials[".Signs_004_O.C.P"]}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube007 as THREE.Mesh).geometry}
              material={materials["CW Anodized med.004"]}
              position={[0.23, 0.84, -0.17]}
              scale={0.25}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={
                  (nodes.Signs_016_yellow_stripes_seamless_damaged_2 as THREE.Mesh).geometry
                }
                material={materials[".Signs_016_yellow_stripes_seamless_damaged_2"]}
                position={[-0.02, 0, 0.16]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.26}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={
                  (nodes.Signs_016_yellow_stripes_seamless_damaged_2001 as THREE.Mesh).geometry
                }
                material={materials[".Signs_016_yellow_stripes_seamless_damaged_2"]}
                position={[-0.02, 1.78, 0.16]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.26}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube012 as THREE.Mesh).geometry}
              material={materials["Material.024"]}
              position={[0.01, 0.28, -0.01]}
              scale={0.25}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube013 as THREE.Mesh).geometry}
              material={materials["CW Anodized med.003"]}
              position={[0.01, 0.28, -0.01]}
              scale={0.25}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube014 as THREE.Mesh).geometry}
              material={materials["CW Anodized med.003"]}
              position={[0.01, 0.28, -0.01]}
              scale={0.25}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube015 as THREE.Mesh).geometry}
              material={materials["CW Anodized med.004"]}
              position={[0.16, 0.21, -0.17]}
              scale={0.25}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.F_Numerical_input_ob_numericalinput_004 as THREE.Mesh).geometry}
                material={materials["S Kevlar"]}
                position={[-0.63, 1.63, 0.77]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.48}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.F_Numerical_input_tx_numericalinput_004 as THREE.Mesh).geometry}
                material={materials["S Text"]}
                position={[-0.63, 1.63, 0.77]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.48}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Signs_013_Lock_right as THREE.Mesh).geometry}
                material={materials[".Signs_013_Lock_right"]}
                position={[0.3, 1.66, 0.51]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.44}
              />
            </mesh>
            <group position={[0.01, 0.28, -0.01]} scale={0.25}>
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube022 as THREE.Mesh).geometry}
                material={materials["CW Anodized med.003"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube022_1 as THREE.Mesh).geometry}
                material={materials["Material.012"]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube017 as THREE.Mesh).geometry}
              material={materials["CW Anodized med.003"]}
              position={[0, 0.2, 0.37]}
              scale={0.25}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube018 as THREE.Mesh).geometry}
              material={materials["CW Anodized med.004"]}
              position={[0.01, 1.55, -0.22]}
              scale={0.25}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cube019 as THREE.Mesh).geometry}
              material={materials["CW Anodized med.003"]}
              position={[0.01, 0.09, -0.13]}
              scale={0.25}
            />
            <group
              position={[-0.11, 0.55, 0.15]}
              rotation={[0, 0, -0.45]}
              scale={0.28}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube258 as THREE.Mesh).geometry}
                material={materials["black.001"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube258_1 as THREE.Mesh).geometry}
                material={materials["Material.016"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube258_2 as THREE.Mesh).geometry}
                material={materials["Material.013"]}
              />
            </group>
            <group
              position={[-0.11, 0.55, 0.23]}
              rotation={[0, 0, -0.45]}
              scale={0.25}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube261 as THREE.Mesh).geometry}
                material={materials["black.001"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube261_1 as THREE.Mesh).geometry}
                material={materials["Material.016"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube261_2 as THREE.Mesh).geometry}
                material={materials["Material.014"]}
              />
            </group>
            <group
              position={[0.11, 0.55, 0.25]}
              rotation={[0, 0, -0.44]}
              scale={0.35}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube268 as THREE.Mesh).geometry}
                material={materials["Material.021"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Cube268_1 as THREE.Mesh).geometry}
                material={materials["Material.019"]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cylinder as THREE.Mesh).geometry}
              material={materials["CW Anodized med.004"]}
              position={[0.27, 0.54, -0.06]}
              rotation={[-0.97, 0, 0]}
              scale={0.25}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cylinder004 as THREE.Mesh).geometry}
              material={materials["Material.016"]}
              position={[0, 1.61, -0.06]}
              scale={0.02}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cylinder005 as THREE.Mesh).geometry}
              material={materials["CW Aluminum matte.001"]}
              position={[0.34, 0.05, -0.23]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={0.01}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cylinder006 as THREE.Mesh).geometry}
              material={materials["CW Aluminum matte.001"]}
              position={[0.29, 0.63, -0.2]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={0.01}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Cylinder007 as THREE.Mesh).geometry}
              material={materials["CW Chrome matte"]}
              position={[0.27, 0.54, -0.07]}
              rotation={[-0.97, 0, 0]}
              scale={0.24}
            />
            <group position={[0, 1.6, -0.06]} scale={0.03}>
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Slice001 as THREE.Mesh).geometry}
                material={materials["CW Anodized med.004"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Slice001_1 as THREE.Mesh).geometry}
                material={materials["Material.003"]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Slice005 as THREE.Mesh).geometry}
              material={materials["CW Plastic dapple.003"]}
              position={[0.01, 0.28, -0.01]}
              scale={0.25}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[1.37, 0.18, 1.15]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035001 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[1.37, -0.7, 1.15]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035002 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[1.37, 0.18, -0.3]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035003 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[1.37, -0.7, -0.3]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Signs_008_Caution as THREE.Mesh).geometry}
                material={materials[".Signs_008_Caution"]}
                position={[1.37, -0.1, 0.48]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.23}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Slice006 as THREE.Mesh).geometry}
              material={materials["CW Plastic dapple.003"]}
              position={[0.01, 0.28, -0.01]}
              scale={0.25}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035004 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[1.37, 0.18, 1.24]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035005 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[1.37, -0.7, 1.24]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035010 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[0.91, 0.18, 1.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035011 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[0.75, -0.35, 1.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.18}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.Examples_035013 as THREE.Mesh).geometry}
                material={materials[".Examples_035.001"]}
                position={[0.75, -0.68, 1.69]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.18}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={(nodes.Slice007 as THREE.Mesh).geometry}
              material={materials["CW Anodized med.003"]}
              position={[0.01, 0.28, -0.01]}
              scale={0.25}
            />
            <group
              position={[0.01, 0.05, 0.31]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={0.09}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.tire_sm005 as THREE.Mesh).geometry}
                material={materials["Prox alum 054"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.tire_sm005_1 as THREE.Mesh).geometry}
                material={materials["Prox kevlar 054"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.tire_sm005_2 as THREE.Mesh).geometry}
                material={materials["Prox easy spec 054"]}
              />
            </group>
            <group
              position={[0.31, 0.05, -0.23]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={0.09}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.tire_sm006 as THREE.Mesh).geometry}
                material={materials["Prox alum 054"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.tire_sm006_1 as THREE.Mesh).geometry}
                material={materials["Prox kevlar 054"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={(nodes.tire_sm006_2 as THREE.Mesh).geometry}
                material={materials["Prox easy spec 054"]}
              />
            </group>
          </group>
        </group>
      );
}

useGLTF.preload("/Forklift_agv_01.glb");
