/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export function ShelfMesh(props: GroupProps) {
    const mesh = useRef(null);
    const { nodes, materials } = useGLTF("/shelf.glb");
    return (
        <group {...props} dispose={null} ref={mesh}>
            <group
                position={[-0.14, -0.1, 0.622]}
                rotation={[0, 0, 0]}
                scale={2.92}
            >
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.defaultMaterial as THREE.Mesh).geometry}
                        material={materials.MAT_ShelfFrame}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.defaultMaterial001 as THREE.Mesh).geometry}
                        material={materials.MAT_ShelfMetal}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/shelf.glb");
