/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { MeshProps } from "@react-three/fiber";

export const GLTF_PATH = "/shelf.glb";

export function ShelfMesh(props: MeshProps) {
    const { nodes, materials } = useGLTF(GLTF_PATH);
    return (
        <mesh {...props}>
            <group
                position={[-0.14, -0.1, 0.622]}
                rotation={[0, 0, 0]}
                scale={2.92}
            >
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.defaultMaterial as THREE.Mesh).geometry}
                        material={materials.MAT_ShelfFrame}
                    />
                    <mesh
                        castShadow
                        receiveShadow
                        geometry={(nodes.defaultMaterial001 as THREE.Mesh).geometry}
                        material={materials.MAT_ShelfMetal}
                    />
                </group>
            </group>
        </mesh>
    );
}

useGLTF.preload(GLTF_PATH);
